// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BO_DotNet_6.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BO_DotNet_6.Context
{
    public partial class TestingContext
    {
        private ITestingContextProcedures _procedures;

        public virtual ITestingContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TestingContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITestingContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SP_GetClientTypeResult>().HasNoKey().ToView(null);
        }
    }

    public partial class TestingContextProcedures : ITestingContextProcedures
    {
        private readonly TestingContext _context;

        public TestingContextProcedures(TestingContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GetClientTypeResult>> SP_GetClientTypeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetClientTypeResult>("EXEC @returnValue = [dbo].[SP_GetClientType]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_TestAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Test]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
